### ISSUE TITLE
2024 11 26

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/policy-wg#111]
# 2024 11 26

Time 0730 PDT / 1530 BST - See the time in your timezone https://everytimezone.com/s/a8399b00

- Chair – Chris Adams (The Green Web Foundation) @mrchrisadams 
- Chair - Lisa McNally (Thoughtworks) @lisamcnally 
- Convener –  Sean Mcilroy (Linux Foundation) @seanmcilroy29 
***
## Antitrust Policy

Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.
***
### Recordings

The Working Group Meeting is [recorded](https://docs.google.com/document/d/1ttKxQE6GweNAI1TCfIq-Fgbv6WIEIuDRbLnIP1ZJ5N8/edit) and is available for members to review until the next scheduled meeting.
***
### Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, GitHub username (optional)

***
## Agenda
- [ ] Approve Agenda / [previous minutes](https://github.com/Green-Software-Foundation/policy-wg/issues/107)

***
## Discussions
 - [x] Policy radar updates ([link to Miro board](https://miro.com/app/board/uXjVLYKR20M=/))
   - Define the Policy areas the GSF should focus on
   - Review policy submission template
- [x] Reaching out to the new W3C Sustainable Web Interest Group for 2025 #108 
- [ ] Defining the PWG 2025 roadmap and supportive articles outlining the current focus.
- [x] [Policy and Regulations](https://github.com/Green-Software-Foundation/policy-wg/issues/110) in the news
***

## AOB
- [ ] Add topics here

***
## Next meeting 
- [x] 10th Dec

***
## Adjourn 
- [ ] Motion to adjourn

-------------------------------------
## Previous Meeting Action Items
- [x] Sean - To schedule a meeting with BCS representative Alex in Q1 2025 to discuss updates and potential areas of collaboration.
> Done - Joint Meeting scheduled for 21st Jan
- [x] Russ will set up a Notion-based policy radar database and interface.
- [x] Chris will follow up on potential collaboration opportunities with the W3C's new "Software Carbon Intensity Web" interest.

**Comment by russelltrow** [comment]
Attended

**Comment by seanmcilroy29** [comment]
### MoM

### Summary meeting notes
The meeting focused on developing and implementing a policy radar to monitor upcoming energy and software policies. Key points included the need for a detailed approach to state-level policies and the importance of engaging influential states. The team discussed the potential impact of new U.S. administration policies on green software and the necessity of creating a toolkit for policymakers. They also considered the idea of organizing a soft lobby day to introduce the Green Software Foundation to decision-makers. The meeting concluded with updates on the W3C's new Sustainable Interest Group and the need for additional input on the policy radar tool.

### Minutes
**Policy Radar and Green Software Advocacy**
Michaela discusses Texas's new energy policies and the importance of green software. Chris explains the policy radar project, which aims to predict future policies and laws affecting green software. 

**Policy Radar Tool Development**
Chris shares the policy radar tool being developed on Miro, which allows users to submit and view policies. Russ emphasizes the importance of finalizing the data schema and gathering sample data to test the tool. Chris shows the current version of the policy radar tool and invites feedback from attendees. Michaela suggests focusing on influential states in the US to ease the data burden.

**Discussion on Policy Toolkit**
Michaela asks about the policy working group's output and suggests creating a policy maker toolkit. Chris agrees and mentions the previous "State of Green Software" report as a potential model. Michaela proposes a lobby day introducing the Green Software Foundation to the new administration. 

**Next Steps and Meeting Conclusion**
Sean will join for further discussions on the W 3C collaboration. Chris will share a list of policy news and invite comments on any immediate actions needed. Michaela will add a recent development about the new Department of Energy head in the US.


### Action Items
- [ ] Try submitting an example policy to the policy radar prototype and provide feedback on the form/data fields.
- [ ] Investigate the possibility of a "lobby day" or other outreach to introduce the Green Software Foundation to the new U.S. administration.
- [ ] Explore creating policy toolkits or other educational materials to help inform policymakers about green software.
Outline

**Comment by mspenharc** [comment]
@seanmcilroy29 My name is misspelled in the meeting notes. Would you mind updating it to the correct spelling (Micalah). Thanks!
