### ISSUE TITLE
2023 12 11

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/policy-wg#60]
# 2023 12 11 Policy WG Agenda / Minutes

Time 0830 PST / 1630 BST - See the time in your timezone https://everytimezone.com/s/a8399b00

- Chair – Chris Adams (The Green Web Foundation)
- Convener –  Sean Mcilroy (Linux Foundation)

## Antitrust Policy

Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings

The Working Group Meeting is [recorded](https://docs.google.com/document/d/1ttKxQE6GweNAI1TCfIq-Fgbv6WIEIuDRbLnIP1ZJ5N8/edit) and is available for members to review until the next scheduled meeting.

### Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, GitHub username (optional)

## Agenda
- [x] Approve Agenda / previous minutes #57 
 
## MoU Review 
- [x] [SustainableIT](https://docs.google.com/document/d/1rTDu9yb94-UvR7KsambCjDBRNJDzZeC78Oj8CjjL_bg/edit) MoU draft.
> Review. MoU submission is currently sitting with SustainableIT's legal dept.
- [x]  Responsible Computing Sync
- Meeting scheduled 22 Jan to discuss approving Draft MoU
> MoU [Draft](https://docs.google.com/document/d/12kyPKBFZAsseF1ATWr9OJ6hDUDCCkiyg/edit).

> Lisa McNally discusses the MOU template for a partnership with Sustainable IT, with input from other members.
The MOU aims to establish a communication channel between the two organizations and explore ways to collaborate, leveraging each other's strengths and resources.
Lisa McNally clarifies that the MOU does not include sponsorship of events in Germany or an overview of the CCF cloud carbon footprint tool.

Lisa McNally mentions the need to identify activities that prioritize education within the sustainable IT group, and proposes that the policy working group could develop a strategy for this. Sean McIlroy suggests that the MOU will provide an opportunity for the sustainable IT group to collaborate with other working groups within GSF, and that the policy working group could help facilitate these conversations. Lisa and Sean discuss standardization group's interaction with GSF working group. Lisa emphasizes the importance of a non-disclosure agreement (NDA) to protect the foundation's intellectual property during collaboration with Sustainable IT.

> Lisa McNally and Namrata propose a partnership with Sustainable IT to support the growth of both communities and nurture the ecosystem. The partnership could involve a shared announcement and leveraging each other's strengths, with Sustainable IT's comms focus complementing GSF's practitioner-building efforts. Chris Adams shared the agenda for the policy Working Group meeting, highlighting the focus on developing a shared understanding of changes to the law and its impact on green software development. The group discussed two examples of how the policy may be implemented, with opportunities for feedback and questions from attendees.

## 2024 Policy Focus
- [x] Review proposed [2024 Policy WG](https://github.com/Green-Software-Foundation/policy-wg/pull/56/files?short_path=b31394e#diff-b31394ea475946268badf45272020cc6a656c3149f1850d835716c50916d689b) roadmap
  - [x] Required Action Items to support 2024 plan
  - [x] First policy [roundtable proposed - specifically for financial services](https://github.com/Green-Software-Foundation/policy-wg/issues/59)
  - [x] GHG protocol outreach conversation (see issue #61 )
  - [x] Attendence at other public fora (i.e. COP)

> Sean suggests the steering committee should discuss and decide on representation at the next COP, with a view to allocating speaking slots or panel participation. Chris Adams notes that a previous decision was made to prioritize internal discussions over attending expensive COP events, but the location of the next COP is still uncertain. Namrata suggests setting up an events committee to bring members together and prioritize competing voices, with the policy working group playing a strong role in expressing a point of view. Chris Adams and Sean McIlroy support the initiative, with Pindi being the driver and Ross capturing the discussion.

> Namrata and Chris discuss the need for focused conversations within the GSF financial services ecosystem to address ESG regulations and challenges. Chris Adams and Sean McIlroy discuss carbon emissions from IT infrastructure with potential interest from Massimo and Michael. Banking sector emissions may be higher than previously thought, with half coming from software use.

> Chris Adams mentions a plan to nominate someone from the group to work on behalf of the GSF and share information. Namrata proposes sharing the opportunity more widely through the mailing list and newsletter. Greenhouse Gas Protocol is seeking technical expertise to address specific areas of improvement, including tracking the carbon intensity of electricity and accounting for digital products with unclear responsibility. Chris Adams suggests using a public issue tracker or mailing list to discuss potential changes to the organization's strategy.

## WG Chair Elections
- [x] Update on the election results (Lisa McNally, Michael Mueller, Chris Adams)

## Upcoming Events
- [x] [Carbon Hack 2024](https://docs.google.com/presentation/d/13IqItz50G3jrsjOlyt4vZtSejUW29TEe/edit#slide=id.g29f073d87a6_1_34)

> Adam provides an update on the hackathon, including dates (February 26 - March 15) and a holding page with more information. Adam discusses the Carbon Hack, an initiative to develop a framework for carbon reduction, open to both GSF members and non-members for a fixed sponsorship price of $5,000. Namrata adds that sponsoring organizations can still participate in the hack, with judges recusing themselves during the judging process.

## Next meeting 
- [x] 08 Jan 2024
> Chris Adams and Sean discuss upcoming events and meeting schedules, with no consensus on a Monday meeting date.
Chris Adams suggests using a Doodle poll to gather opinions on moving the meeting time, which Sean McIlroy agrees to work on. The group discussed moving the meeting time to accommodate new members who could not attend the previous meeting.

## Adjourn 
- [x] Motion to adjourn
--------

## Previous Meeting Action Items
- [ ] Nothing outstanding

**Comment by lisamcnally** [comment]
Attended.

**Comment by chargao** [comment]
Attended

**Comment by mcrubellati** [comment]
Attended

**Comment by muemich** [comment]
attended

**Comment by mrchrisadams** [comment]
Attended

**Comment by seanmcilroy29** [comment]
Attended

**Comment by seanmcilroy29** [comment]
Approved
